### ISSUE TITLE
Can we use jetstack/kube-oidc-proxy without Dex And Gangway 

### ISSUE THREAD

**Issue by venky999** [jetstack/kube-oidc-proxy#139]
Can we use jetstack/kube-oidc-proxy without Dex And Gangway to authenticate directly with OIDC providers like Google, Microsoft or Okta 

The reason for my question is there is no option to specify `client_secret` in the OIDC config and more over its not clear how does the kubeconfig look like 

The README says we need to provide `id-token, refresh-token` but not sure how to get these values without something like DEX automatically..

**Comment by JoshVanL** [comment]
Hi there!

kube-oidc-proxy is agnostic to any OIDC provider. It may be helpful to look at documentation for the specific provider you want against the API server since the configuration there will be identical.
