### ISSUE TITLE
Support HTTPS_PROXY env variable

### ISSUE THREAD

**Issue by geoberle** [jetstack/kube-oidc-proxy#153]
I would really love to see some option to let kube-oidc-proxy know that it should use a specific HTTP proxy for communication with the upstream Kubernetes API.

I tried the usual HTTP_PROXY and https_proxy ENV variables but without success. Is there a way i'm not aware of?

Thanks for looking into this.

**Comment by JoshVanL** [comment]
Hello!

Thanks for the issue. This seems like a simple fix - I will open a PR shortly.

/assign

**Comment by geoberle** [comment]
Hi. Wow that was quick. Thank you so much for your effort!
