### ISSUE TITLE
Need the ability to prefix the users and groups that we impersonante

### ISSUE THREAD

**Issue by nickperry** [jetstack/kube-oidc-proxy#74]
Kubernetes API server OIDC provides the options oidc-username-prefix and oidc-groups-prefix.

At our site, for example we set

oidc-username-prefix=oidc:
oidc-groups-prefix=oidc:

This is a good practice as it makes it very obvious what sort of user and group we're dealing with, for example when looking at audit logs.

All of our role bindings for human users are based on this. Unfortunately this breaks when we use kube-oidc-proxy because although the full suite of oidc options are listed when you run kube-oidc-proxy -h, not all of them take effect.

It seems reasonable that kube-oidc-proxy should implement oidc-username-prefix and oidc-groups-prefix.

**Comment by JoshVanL** [comment]
Thanks for bringing this up, an oversight by me

/kind bug
/assign

**Comment by nickperry** [comment]
Sorry @JoshVanL . This is really embarrassing for me as I've seen the work you've put into https://github.com/jetstack/kube-oidc-proxy/pull/75/commits/546c18e08c02da7cbfa74c06e0f73a689408bdc5, but, I was mistaken - it actually worked already. I had a misconfiguration in my environment when I raised this issue.

I owe you a 🍺.
![image](https://user-images.githubusercontent.com/159528/60923468-da228400-a296-11e9-8d6a-9d4c56675636.png)

**Comment by JoshVanL** [comment]
Whoops! :grimacing: 
No harm done, my fault also for not checking!

Glad it working as expected :) 

/close
