### ISSUE TITLE
Investigate why  NGINX doesn't work

### ISSUE THREAD

**Issue by JoshVanL** [jetstack/kube-oidc-proxy#9]
When deploying behind an nginx, the kube-oidc-proxy becomes unreachable - due to some streaming error.

This is basically a requirement for a cert-manager cert bootstrap.

Logs TBD.

**Comment by ragarcia26** [comment]
I'm confused and am having trouble deploying oidc-proxy behind an nginx ingress controller. Is this not possible, will it ever be, use X instead?
